### ISSUE TITLE
大佬，python新手求教一个问题

### ISSUE THREAD

**Issue by codeisphilosophy** [smallevilbeast/ntchat#12]
大佬你好，我又产生两个问题想请教一下你。

1. wechat.get_contact_detail函数返回的数据是什么类型的。

![1的代码](https://user-images.githubusercontent.com/112748029/188294749-9b2f660d-5130-46b5-be93-8b942846cb1b.png)

![1的结果](https://user-images.githubusercontent.com/112748029/188294755-7a7364a7-c505-46b9-824d-85021a558463.png)

![get_contct_detail函数定义](https://user-images.githubusercontent.com/112748029/188294990-d3425bf5-a756-4632-afdc-db3834bbe271.png)

**Comment by smallevilbeast** [comment]
晚上看下

**Comment by smallevilbeast** [comment]
升级下ntchat

pip install -i https://pypi.tuna.tsinghua.edu.cn/simple -U ntchat
