### ISSUE TITLE
向微信群发送文件没发送成功，也没报错

### ISSUE THREAD

**Issue by sheenzxx** [smallevilbeast/ntchat#18]
wechat.send_file(to_wxid="xxxxxxxx@chatroom", file_path='E:\\\\sheen\\\\script\\\\python3\\\\文件1.xlsx')

看到日志如下。但是群里没接收到文件
2022-09-07 15:02:07,911 - WeChatInstance - DEBUG - communicate wechat pid: 11488,  data: {'type': 11041, 'data': {'to_wxid': 'xxxxxxx@chatroom', 'file': 'E:\\\\sheen\\\\script\\\\python3\\\\文件1.xlsx'}}

**Comment by smallevilbeast** [comment]
能提供例子吗 我测试是可以的

**Comment by sheenzxx** [comment]
import sys
import ntchat

wechat = ntchat.WeChat()
trace_code={}

wechat.open(smart=True)

wechat.wait_login()

wechat.send_file(to_wxid="xxxxxx@chatroom", file_path='E:\\sheen\script\\python3\\文件1.xlsx')

try:
    while True:
        pass
except KeyboardInterrupt:
    ntchat.exit_()
    sys.exit()

python 版本 3.8.5  。操作系统 windows 10

![企业微信截图_16626874925796](https://user-images.githubusercontent.com/3350015/189254707-15ddce29-740b-43a9-baf6-5e06be2cf2f7.png)

**Comment by msechen** [comment]
我也遇到这个问题，给联系人发图片，不报错，实际没有发送成功
另外问一点，文件或者图片地址支持远程url吗？例如http://www.xxxxxx.com/ex.jpg
