### ISSUE TITLE
有没有检测心跳的

### ISSUE THREAD

**Issue by tpaccount** [smallevilbeast/ntchat#2]
能不能  如果运行过程中 PC端微信下线，那么我就退出这应用？
try:
    while True:
        pass
except KeyboardInterrupt:
    # 在这里加心跳判断 ？？
    ntchat.exit_()
    sys.exit()

**Comment by smallevilbeast** [comment]
不用心跳， 有退出会通知的, 监听MT_USER_LOGOUT_MSG消息

```python
@wechat.msg_register(ntchat.MT_USER_LOGOUT_MSG)
def on_wechat_quit(wechat, message):
    print("########这里做一些退出的工作###########")
    print(message)
```
