### ISSUE TITLE
希望可以自行调整log等级

### ISSUE THREAD

**Issue by kressety** [smallevilbeast/ntchat#24]
不然运行一段时间后终端上显示太多的信息，看不到自己的流程是否被正常执行

**Comment by kressety** [comment]
#25 简单做了一些修改

**Comment by smallevilbeast** [comment]
目前也是支持的  https://github.com/smallevilbeast/ntchat/blob/master/docs/FAQ.md#5-%E5%A6%82%E4%BD%95%E5%85%B3%E9%97%ADntchat%E7%9A%84%E6%97%A5%E5%BF%97
