### ISSUE TITLE
发送文件或者图片的时候，文件路径会被编码，无法发送文件

### ISSUE THREAD

**Issue by msechen** [smallevilbeast/ntchat#26]
![1663208554(1)](https://user-images.githubusercontent.com/74814336/190298414-3fdf30ae-a885-407e-9c64-d73c606d1ac3.jpg)

代码如下

import sys
import time
import ntchat

wechat = ntchat.WeChat()

wechat.open(smart=True)

wechat.wait_login()

wechat.send_image(to_wxid="xxxxxxxxxxxxx", file_path="D:\1.jpg")

try:
    while True:
        time.sleep(0.5)
except KeyboardInterrupt:
    ntchat.exit_()
    sys.exit()

**Comment by Sencc** [comment]
"D:\1.jpg" 路径要用反斜杠

**Comment by kressety** [comment]
转义问题，改成
```python
wechat.send_image(to_wxid="xxxxxxxxxxxxx", file_path="D:\\1.jpg") #或者
wechat.send_image(to_wxid="xxxxxxxxxxxxx", file_path=r"D:\1.jpg") #或者
wechat.send_image(to_wxid="xxxxxxxxxxxxx", file_path="D:/1.jpg")
```

**Comment by msechen** [comment]
多谢两位大佬，有ntchat微信交流群吗？求拉

**Comment by smallevilbeast** [comment]
可以进qq群
