### ISSUE TITLE
在执行过程中顿卡现象

### ISSUE THREAD

**Issue by sheenzxx** [smallevilbeast/ntchat#34]
代码在CMD 窗口执行过程中。经常会出现没有日志。然后在窗口敲下回车。日志就出来。同时才把消息发送到微信里面去。好像ntchat 挟持住了消息。但没有推送到微信的windows 窗口。敲了回车才推送过去

**Comment by smallevilbeast** [comment]
更新到最新版本

**Comment by smallevilbeast** [comment]
pip install -U ntchat

**Comment by sheenzxx** [comment]
好的，谢谢
