### ISSUE TITLE
send_xml这个接口提示成功了，实际上没成功啊。

### ISSUE THREAD

**Issue by umeitime** [smallevilbeast/ntchat#39]
send_xml 我发送内容是表情包或者图片，都无法成功。

**Comment by smallevilbeast** [comment]
send_xml只能发小程序，链接，视频号等

并且需要把xml中的fromusername改成自己的wxid再发

**Comment by umeitime** [comment]
> send_xml只能发小程序，链接，视频号等
> 
> 并且需要把xml中的fromusername改成自己的wxid再发

请教下表情如何发送？

**Comment by smallevilbeast** [comment]
动图gif, emoji,还是表情包？

**Comment by umeitime** [comment]
> 动图gif, emoji,还是表情包？

表情包。

**Comment by smallevilbeast** [comment]
表情包还不支持
