### ISSUE TITLE
微信登录环境存在异常 为了帐号安全 本次登录已失效

### ISSUE THREAD

**Issue by linpeisensh** [smallevilbeast/ntchat#40]
感谢大佬写的方法，非常好用。

问题是消息发多了（期望发700人，目前发100人左右），会被微信退登。

请问大佬有啥解决办法吗？

期待大佬回复。

**Comment by smallevilbeast** [comment]
频率太快或是新环境登录

**Comment by linpeisensh** [comment]
@smallevilbeast 感谢大佬回答。这个问题，通过发有细微差别的信息解决（至少在出另一个问题前没有再次报错）。
新问题是：文件发送过多，该微信已无法发送文件（包括给自己发文件），所有发送文件显示，发送中断。然而代码没有报错，不停地发送信息，却发不出文件。
![img_v2_5b6b5c67-9a3a-4e17-959a-2cc856b5cdbg](https://user-images.githubusercontent.com/52672986/192100610-446337e1-d3d6-41c0-a401-88a7e5b15b97.jpg)

1.大佬对于这种情况有啥让它报错的手段吗？
2.大佬知道微信的文件发送有啥限制（累积次数，累积大小）吗？有办法突破吗？没法突破的话大概多久能解封？

**Comment by smallevilbeast** [comment]
不清楚

**Comment by linpeisensh** [comment]
再次打扰大佬，请问这个包有接口能检测到微信系统消息吗？比如“操作过于频繁，可稍后再试”。
![img_v2_02d78fe6-6085-4e85-9deb-1a40b3a7144g](https://user-images.githubusercontent.com/52672986/192276087-95fe7d4d-9ad8-4711-985c-6414abb48185.jpg)

**Comment by linpeisensh** [comment]
@smallevilbeast 打扰大佬，能看看我这个问题吗？可以收到这个提示吗？
https://github.com/smallevilbeast/ntchat/issues/40#issuecomment-1257959471
