### ISSUE TITLE
{"detail":"There was an error parsing the body"}

### ISSUE THREAD

**Issue by Toy-Jie** [smallevilbeast/ntchat#42]
通过HttpApi调用/msg/send_text接口

发送 测试* 没问题
发送 测*试 就会出现There was an error parsing the body

**Comment by Toy-Jie** [comment]
**自动发送@
自动发送~**
以上两个没问题

**自动发送!**
这个就不行了

**Comment by smallevilbeast** [comment]
你可以使用 http://127.0.0.1:8000/docs 测试下 

我刚测试没有问题，你是用代码访问的吗，可以提供下相关例子
