### ISSUE TITLE
关于打包后提示微信版本错误问题

### ISSUE THREAD

**Issue by CJ-from-LosSantos** [smallevilbeast/ntchat#43]
![image](https://user-images.githubusercontent.com/63846405/192747778-3cb16ef7-30f9-416f-951d-3d4b15874f9c.png)

如果将项目打包成exe，ntchat会提出版本错误问题，但是很显然版本是一致的，因为在ide中他是可以运行的。
希望得到您的解答

**Comment by CJ-from-LosSantos** [comment]
很简单，你可以直接尝试pyinstaller打包即可

**Comment by smallevilbeast** [comment]
注意看常见问题说明：
