### ISSUE TITLE
无法使用wechat.open(smart=True)唤起登录窗口

### ISSUE THREAD

**Issue by littlepanda0716** [smallevilbeast/ntchat#54]
运行环境：macos中通过Parallels Desktop安装的windows 11 pro版本
问题说明：在上述环境中安装3.6.0.18版本微信后，未打开微信时在python中执行wechat.open(smart=True)时无法唤起登陆窗口，且通过资源管理器查看后台也没有微信相关后台程序。在已打开微信窗口时执行wechat.open()，会发生微信窗口关闭、弹出错误报告窗口，在关闭错误报告窗口后会弹出新的微信窗口，需要登陆账号，但登陆账号后wechat.wait_login()一直保持等待状态。

**Comment by smallevilbeast** [comment]
看这个文档  指定下微信路径看看 

https://github.com/smallevilbeast/ntchat/blob/master/docs/FAQ.md#1-wechatversionnotmatcherror%E5%BC%82%E5%B8%B8

**Comment by littlepanda0716** [comment]
您好，非常感谢您的回复，尝试按照指定路径和版本的方法之后，目前还是一样的状态。或者是否有什么办法可以获取已打开的微信程序pid，然后使用wechat.attch()的方法关联上吗？

**Comment by smallevilbeast** [comment]
```bash
pip install psutil
```

```python
import psutil
import ntchat


def get_wechat_pids():
    pids = []
    for proc in psutil.process_iter(['pid', 'name']):
        if proc.name().lower() == "wechat.exe":
            pids.append(proc.pid)
    return pids


for pid in get_wechat_pids():
    wechat = ntchat.WeChat()
    wechat.attach(pid)


try:
    while True:
        pass
except KeyboardInterrupt:
    ntchat.exit_()
```

**Comment by littlepanda0716** [comment]
通过attach的方法也会提示错误报告，并重新打开了一个微信客户端。请问目前在win11中是可以正常使用的是吗？推测可能因为目前运行环境是虚拟机的关系

**Comment by smallevilbeast** [comment]
win11 可以正常使用的， 你打开微信看下版本 感觉是版本不对

**Comment by smallevilbeast** [comment]
登录后看下  设置-》关于微信

**Comment by littlepanda0716** [comment]
<img width="552" alt="image" src="https://user-images.githubusercontent.com/5668498/194745974-7284af31-edef-4c46-89dc-3bf16248dcd9.png">
是从您github项目中提供的微信链接下载的，请朋友在win10电脑上测试是没问题的

**Comment by smallevilbeast** [comment]
进qq群 加我下

**Comment by littlepanda0716** [comment]
已加
