### ISSUE TITLE
始终报错：ntchat.exception.WeChatVersionNotMatchError

### ISSUE THREAD

**Issue by tommickey2020** [smallevilbeast/ntchat#56]
检查了以下几点：
1、wechat.exe版本：3.6.0.18
2、安装路径为默认目录：C:\Program Files (x86)\Tencent\WeChat
3、注册表：
[HKEY_CURRENT_USER\SOFTWARE\Tencent\WeChat]
"Version"=dword:63060012
"InstallPath"="C:\Program Files (x86)\Tencent\WeChat"
4、增加了以下代码到测试py文件里：
import ntchat

# wechat_exe_path设置成自己3.6.0.18版本的微信的安装路径
ntchat.set_wechat_exe_path(
    wechat_exe_path=r"C:\Program Files (x86)\Tencent\WeChat\WeChat.exe", 
    wechat_version="3.6.0.18")

5、测试程序test.py代码：
# -*- coding: utf-8 -*-
import sys
import time
import ntchat

# wechat_exe_path设置成自己3.6.0.18版本的微信的安装路径
ntchat.set_wechat_exe_path(
    wechat_exe_path=r"C:\Program Files (x86)\Tencent\WeChat\WeChat.exe",
    wechat_version="3.6.0.18")

wechat = ntchat.WeChat()

# 打开pc微信, smart: 是否管理已经登录的微信
wechat.open(smart=True)

# 等待登录
wechat.wait_login()

# 获取联系人列表并输出
contacts = wechat.get_contacts()

print("联系人列表: ")
print(contacts)

# 以下是为了让程序不结束，如果有用于PyQt等有主循环消息的框架，可以去除下面代码
try:
    while True:
        time.sleep(0.5)
except KeyboardInterrupt:
    ntchat.exit_()
    sys.exit()

6、执行以上代码始终报错：ntchat.exception.WeChatVersionNotMatchError
求支持！谢谢！

**Comment by smallevilbeast** [comment]
是打包后吗

**Comment by liuxuanye888** [comment]
我也遇到了这个问题

**Comment by liuxuanye888** [comment]
打包后，
![image](https://user-images.githubusercontent.com/58730545/194794190-cdccb742-0efd-441f-aa9e-56eb6ea0a3fb.png)

**Comment by smallevilbeast** [comment]
看常见问题说明 pyinstaller打包相关

https://github.com/smallevilbeast/ntchat/blob/master/docs/FAQ.md#7-pyinstaller%E6%89%93%E5%8C%85exe

**Comment by liuxuanye888** [comment]
解决了，谢谢楼主
