### ISSUE TITLE
有方法能检测到微信系统消息吗？比如“操作过于频繁，可稍后再试”

### ISSUE THREAD

**Issue by linpeisensh** [smallevilbeast/ntchat#72]
感谢大佬，想向大佬咨询，是否有以下功能的方法：
1.有方法能检测到微信系统消息吗？比如下图的“操作过于频繁，可稍后再试” 
![img_v2_02d78fe6-6085-4e85-9deb-1a40b3a7144g](https://user-images.githubusercontent.com/52672986/197212106-ce7587d9-2de5-450e-8892-ba0683794062.jpg)
2.能检测到发送文件失败
![img_v2_5b6b5c67-9a3a-4e17-959a-2cc856b5cdbg](https://user-images.githubusercontent.com/52672986/197212194-b00ea0ac-bf9b-4be1-8594-bc7f5f629f08.jpg)
感谢大佬！

**Comment by smallevilbeast** [comment]
不能
