### ISSUE TITLE
请问message中的raw_msg能解析吗？

### ISSUE THREAD

**Issue by cqboyone** [smallevilbeast/ntchat#9]
大佬你提供的微信客户端没法自动下载视频，所以我没法从video这个字段的路径拿到视频文件。请问message中的raw_msg能解析吗？有没有办法能实现视频自动下载？因为我想把视频和图片都存NAS，现在图片是实现了。

**Comment by smallevilbeast** [comment]
视频也是有路径的吧

**Comment by cqboyone** [comment]
> 视频也是有路径的吧

有的，但是微信客户端不会自动下载视频。要点击下载，那个视频路径才会生成视频文件。

**Comment by cqboyone** [comment]
之前小于200M的视频无法自动下载，今天起来一看，又可以了。我再观察下。
